apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  annotations:
    'backstage.io/kubernetes-id': my-kubernetes-component2
  name: my-kubernetes-component2
spec:
  lifecycle: production
  owner: my-team
  type: service
